### ISSUE TITLE
[Rinkeby] Recipient address is invalid

### ISSUE THREAD

**Issue by pedrouid** [PrimaBlock/presale-pool#10]
# BUG
I was testing Primablock on Rinkeby when I created a pool, I took the smart contract bytecode to myetherwallet and signed with Metamask but when I went to confirm the transaction to deploy the contract it gave me an error message: 
"Recipient address is invalid. Sending this transaction will result in a loss of ETH."
I checked the contract address and it showed empty (simply "0x")

Not sure if this is only happening on the Rinkeby testnet but I will attach screenshots of all steps bellow for better understanding.

# PRIMABLOCK - POOL SETTINGS
<img width="607" alt="screenshot 2017-11-28 13 06 12" src="https://user-images.githubusercontent.com/10136079/33321395-7001d57c-d43d-11e7-935f-2a9099e4f472.png">

# MYETHERWALLET - DEPLOY CONTRACT
<img width="1710" alt="screenshot 2017-11-28 13 06 17" src="https://user-images.githubusercontent.com/10136079/33321396-701b722a-d43d-11e7-8e2f-1105e6dc49d1.png">

# METAMASK - CONFIRM TRANSACTION FOR CONTRACT
<img width="1920" alt="screenshot 2017-11-28 13 06 00" src="https://user-images.githubusercontent.com/10136079/33321394-6fe9d490-d43d-11e7-9fed-dde0c2f02046.png">

**Comment by tamirms** [comment]
@pedrouid this is a bug in myetherwallet see https://github.com/kvhnuke/etherwallet/issues/1421
