### ISSUE TITLE
Safeguarding participants' rights

### ISSUE THREAD

**Issue by thomasengesland** [PrimaBlock/presale-pool#6]
Hi. I find this project very interesting and have a question.

Do this smart contract ensure that the participants are guaranteed to have either their pre sale tokens or refund transferred to them?

A reference to what part of the contract handles this would be highly appreciated.

**Comment by tamirms** [comment]
@thomasengesland there's no such guarantee. you have to trust who ever is managing the pool to keep their end of the bargain
